### ISSUE TITLE
Publish package for current project locally

### ISSUE THREAD

**Issue by einari** [dolittle-tools/common#32]
Build - pack and Update the .nuget/packages folder for more rapid cross GitHub repository work (think DotNET.Fundamentals -> Runtime -> DotNET.SDK)

child of #10

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1124957467633577)

**Comment by woksin** [comment]
This is achieved by using npm link or simply creating symlinks
