### ISSUE TITLE
Setup Azure DevOps pipelines 

### ISSUE THREAD

**Issue by woksin** [dolittle-tools/common#33]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1125254808126130)

**Comment by einari** [comment]
➤ Sindre Wilting commented:

This is 'nice to have' and can be done when no other tasks are at hand

**Comment by einari** [comment]
It is not a nice to have, its in fact very critical that everything we build is automated on build and deployed. But will move it over to Mathieu Minguez ( https://app.asana.com/0/1130228495330205/list ) as he has gained a lot of experience with Azure DevOps.

**Comment by einari** [comment]
Sindre Wilting ( https://app.asana.com/0/1116545856664150/list ) already started a pipeline for TypeScript, which is what ths project is built on: https://github.com/dolittle-tools/AzureDevOps/pull/1/files

**Comment by einari** [comment]
➤ Tore Eggen commented:

@Mathieu Minguez ( https://app.asana.com/0/1130228495330205/list ) Does this belong in any of the milestones or stories that you are working on? This one syncs to github
