### ISSUE TITLE
Introduce the concept of a context and the ability to log into one using device code flow

### ISSUE THREAD

**Issue by einari** [dolittle-tools/common#55]
## Background

The goal is to allow anyone to take any of our building blocks and run it anywhere. This actual environment it is running in, is what we refer to as a context. It will hold the different exposed Dolittle services that gets installed and the tooling typically then having the ability to talk to the endpoints of this - relative to the URL typically.

By default, there is the official environment - which is the Dolittle offering - meaning we can provide an optimized mechanism for just logging into it and it would then automatically create a “Dolittle Official” environment or similar and that would be the one logged in. 

## Commands

All examples are given in the context of the CLI.

### Contexts - namespace

A context is a representation of where to find Dolittle services. These are given a name and has an endpoint that represents where the API surface for these servies are. The user needs to be authenticated in order to work with it and for now we want to keep the access token and the refresh token from an [OAuth Device Flow](https://medium.com/identityserver/an-introduction-to-the-oauth-device-flow-75ad71c78872).

#### Add

Adds a context with a given name and URL

```shell
$ dolittle contexts add <name> <url>
```

#### Remove

Remove a context - it should also have a «Are you sure?» confirmation from the user.

```shell
$ dolittle contexts remove <name>
```

#### List

List all environments

```shell
$ dolittle contexts list
``` 

Result should be in a table

### Login

Logs the user into a context. Since this is a top level command, it means it implicitly means you’re logging into a context. This is to provide a simpler syntax as a starting point and not having to require the `contexts` namespace.

The default starting point for anyone using the official Dolittle context in the cloud (https://dolittle.studio) - the procedure should be a very simple login without any arguments or options:

```shell
$ dolittle login
``` 

If you have another context you need to log into that has e.g. Access tokens that are no longer valid, you can optionally provide the name of this:

```shell
$ dolittle login <name of environment>
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1138564886656018)

**Comment by woksin** [comment]
Most of the functionalities described here is implemented for the 8.1.0 release.
