### ISSUE TITLE
When creating things like concepts, it would be nice if it could recognise basic types and pull in the correct namespace

### ISSUE THREAD

**Issue by einari** [dolittle-tools/common#8]
C# boilerplate related:

Today when creating a concept and you specify the type, it does not add the using statement for the type. Obviously, we can't know about all the types - but things like String/string, Guid and primitives in the .NET space. 

Since we eventually will have multi-language support, we should figure out a way to make this language specific and something the "language renderer" can add to the boilerplates - maybe this is related to slots that we've talked about.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1124979611439466)

**Comment by woksin** [comment]
Does not belong here. Belongs in the [runtime plugin](https://github.com/dolittle-runtime/Runtime)
